import = [
    "~/AppData/Roaming/alacritty/themes/nordic.toml" # "~/AppData/Roaming/alacritty/themes/ayu_light.toml"
]

working_directory =  "/Users/Pau/"





[font]

normal.family = "JetBrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"

size = 12.0

[window]

decorations = "Full"
startup_mode =  "Windowed"
title = "Terminal"
dynamic_title = false

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }


[shell]
program = "/Users/Pau//AppData/Local/Microsoft/WindowsApps/Microsoft.PowerShell_8wekyb3d8bbwe/pwsh.exe"

[terminal]
osc52 = "CopyPaste"